-- sharkAttend production schema
create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  employee_no text not null unique check (employee_no ~ '^[0-9]+$'),
  name text not null,
  role text not null default 'employee' check (role in ('employee','admin')),
  created_at timestamptz not null default now()
);
create table if not exists public.attendance_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  work_date date not null,
  clock_in timestamptz,
  clock_out timestamptz,
  created_at timestamptz not null default now(),
  constraint attendance_order check (clock_out is null or (clock_in is not null and clock_out >= clock_in)),
  constraint attendance_one_day unique (user_id, work_date)
);
create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  category text not null default 'general' check (category in ('general','attendance','holiday','event','important','system')),
  created_by uuid references auth.users(id) on delete set null,
  published_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);
create table if not exists public.employee_permissions (
  user_id uuid primary key references auth.users(id) on delete cascade,
  can_manage_employees boolean not null default false,
  can_manage_permissions boolean not null default false,
  can_reset_passwords boolean not null default false,
  can_manage_announcements boolean not null default false,
  can_manage_attendance boolean not null default false,
  updated_at timestamptz not null default now()
);
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  title text not null,
  body text not null,
  kind text not null default 'general' check (kind in ('general','attendance','announcement','important','system')),
  created_at timestamptz not null default now(),
  expires_at timestamptz
);
create table if not exists public.attendance_settings (
  id integer primary key default 1 check (id=1),
  work_start time not null default '09:00',
  work_end time not null default '18:00',
  late_grace_minutes integer not null default 0 check (late_grace_minutes between 0 and 180),
  updated_at timestamptz not null default now()
);
insert into public.attendance_settings(id) values(1) on conflict(id) do nothing;
create table if not exists public.employee_schedules (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  work_date date not null,
  start_time time,
  end_time time,
  is_workday boolean not null default true,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id,work_date),
  check ((is_workday=false) or (start_time is not null and end_time is not null))
);
create table if not exists public.leave_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  leave_type text not null check (leave_type in ('annual','sick','personal','unpaid')),
  start_date date not null,
  end_date date not null,
  reason text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  reviewer_id uuid references auth.users(id),
  reviewed_at timestamptz,
  review_note text,
  created_at timestamptz not null default now(),
  check (end_date>=start_date)
);
create table if not exists public.correction_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  work_date date not null,
  requested_clock_in timestamptz,
  requested_clock_out timestamptz,
  reason text not null,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  reviewer_id uuid references auth.users(id),
  reviewed_at timestamptz,
  review_note text,
  created_at timestamptz not null default now(),
  check (requested_clock_in is not null or requested_clock_out is not null),
  check (requested_clock_out is null or requested_clock_in is null or requested_clock_out>=requested_clock_in)
);

create schema if not exists private;
create or replace function private.is_admin() returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.profiles where user_id=auth.uid() and role='admin');
$$;
revoke all on function private.is_admin() from public,anon;
grant execute on function private.is_admin() to authenticated;

alter table public.profiles enable row level security;
alter table public.attendance_records enable row level security;
alter table public.announcements enable row level security;
alter table public.employee_permissions enable row level security;
alter table public.notifications enable row level security;
alter table public.attendance_settings enable row level security;
alter table public.employee_schedules enable row level security;
alter table public.leave_requests enable row level security;
alter table public.correction_requests enable row level security;

grant select on public.profiles,public.attendance_records,public.announcements,public.employee_permissions,public.notifications,public.attendance_settings to authenticated;
grant select,insert,update,delete on public.employee_schedules to authenticated;
grant select,insert,update on public.leave_requests,public.correction_requests to authenticated;

drop policy if exists profiles_read_self_or_admin on public.profiles;
create policy profiles_read_self_or_admin on public.profiles for select to authenticated using (auth.uid()=user_id or private.is_admin());
drop policy if exists attendance_read_own_or_admin on public.attendance_records;
create policy attendance_read_own_or_admin on public.attendance_records for select to authenticated using (auth.uid()=user_id or private.is_admin());
drop policy if exists announcements_read_authenticated on public.announcements;
create policy announcements_read_authenticated on public.announcements for select to authenticated using(true);
drop policy if exists permissions_read_own on public.employee_permissions;
create policy permissions_read_own on public.employee_permissions for select to authenticated using(auth.uid()=user_id);
drop policy if exists notifications_read_relevant on public.notifications;
create policy notifications_read_relevant on public.notifications for select to authenticated using(user_id is null or user_id=auth.uid());
drop policy if exists attendance_settings_read on public.attendance_settings;
create policy attendance_settings_read on public.attendance_settings for select to authenticated using(true);
drop policy if exists schedules_read_self_or_admin on public.employee_schedules;
create policy schedules_read_self_or_admin on public.employee_schedules for select to authenticated using(user_id=auth.uid() or private.is_admin());
drop policy if exists schedules_admin_insert on public.employee_schedules;
create policy schedules_admin_insert on public.employee_schedules for insert to authenticated with check(private.is_admin());
drop policy if exists schedules_admin_update on public.employee_schedules;
create policy schedules_admin_update on public.employee_schedules for update to authenticated using(private.is_admin()) with check(private.is_admin());
drop policy if exists schedules_admin_delete on public.employee_schedules;
create policy schedules_admin_delete on public.employee_schedules for delete to authenticated using(private.is_admin());
drop policy if exists leave_read_self_or_admin on public.leave_requests;
create policy leave_read_self_or_admin on public.leave_requests for select to authenticated using(user_id=auth.uid() or private.is_admin());
drop policy if exists leave_insert_self on public.leave_requests;
create policy leave_insert_self on public.leave_requests for insert to authenticated with check(user_id=auth.uid());
drop policy if exists leave_admin_update on public.leave_requests;
create policy leave_admin_update on public.leave_requests for update to authenticated using(private.is_admin()) with check(private.is_admin());
drop policy if exists correction_read_self_or_admin on public.correction_requests;
create policy correction_read_self_or_admin on public.correction_requests for select to authenticated using(user_id=auth.uid() or private.is_admin());
drop policy if exists correction_insert_self on public.correction_requests;
create policy correction_insert_self on public.correction_requests for insert to authenticated with check(user_id=auth.uid());
drop policy if exists correction_admin_update on public.correction_requests;
create policy correction_admin_update on public.correction_requests for update to authenticated using(private.is_admin()) with check(private.is_admin());

create or replace function public.clock_attendance(p_action text) returns public.attendance_records language plpgsql security definer set search_path='' as $$
declare v_uid uuid:=auth.uid();v_now timestamptz:=now();v_work_date date:=(v_now at time zone 'Asia/Taipei')::date;v_row public.attendance_records;
begin
 if v_uid is null then raise exception 'Not authenticated'; end if;
 if p_action not in ('in','out') then raise exception 'Invalid action'; end if;
 if p_action='in' then insert into public.attendance_records(user_id,work_date,clock_in) values(v_uid,v_work_date,v_now) on conflict(user_id,work_date) do nothing returning * into v_row;if v_row.id is null then raise exception 'Already clocked in today'; end if;
 else update public.attendance_records set clock_out=v_now where user_id=v_uid and work_date=v_work_date and clock_in is not null and clock_out is null returning * into v_row;if v_row.id is null then raise exception 'No open clock-in found today'; end if;end if;
 return v_row;
end;$$;
revoke execute on function public.clock_attendance(text) from public,anon;
grant execute on function public.clock_attendance(text) to authenticated;

create or replace function public.update_attendance_settings(p_start time,p_end time,p_grace integer) returns void language plpgsql security definer set search_path='' as $$
begin if auth.uid() is null or not private.is_admin() then raise exception 'Forbidden';end if;update public.attendance_settings set work_start=p_start,work_end=p_end,late_grace_minutes=p_grace,updated_at=now() where id=1;end;$$;
revoke execute on function public.update_attendance_settings(time,time,integer) from public,anon;
grant execute on function public.update_attendance_settings(time,time,integer) to authenticated;
create or replace function public.review_leave_request(p_id bigint,p_status text,p_note text default null) returns void language plpgsql security definer set search_path='' as $$
begin if auth.uid() is null or not private.is_admin() then raise exception 'Forbidden';end if;if p_status not in ('approved','rejected') then raise exception 'Invalid status';end if;update public.leave_requests set status=p_status,reviewer_id=auth.uid(),reviewed_at=now(),review_note=p_note where id=p_id and status='pending';if not found then raise exception 'Request not found or already reviewed';end if;end;$$;
revoke execute on function public.review_leave_request(bigint,text,text) from public,anon;
grant execute on function public.review_leave_request(bigint,text,text) to authenticated;
create or replace function public.review_correction_request(p_id bigint,p_status text,p_note text default null) returns void language plpgsql security definer set search_path='' as $$
declare r public.correction_requests;existing public.attendance_records;begin if auth.uid() is null or not private.is_admin() then raise exception 'Forbidden';end if;if p_status not in ('approved','rejected') then raise exception 'Invalid status';end if;select * into r from public.correction_requests where id=p_id and status='pending' for update;if r.id is null then raise exception 'Request not found or already reviewed';end if;if p_status='approved' then select * into existing from public.attendance_records where user_id=r.user_id and work_date=r.work_date;if existing.id is null then insert into public.attendance_records(user_id,work_date,clock_in,clock_out) values(r.user_id,r.work_date,r.requested_clock_in,r.requested_clock_out);else update public.attendance_records set clock_in=coalesce(r.requested_clock_in,clock_in),clock_out=coalesce(r.requested_clock_out,clock_out) where id=existing.id;end if;end if;update public.correction_requests set status=p_status,reviewer_id=auth.uid(),reviewed_at=now(),review_note=p_note where id=p_id;end;$$;
revoke execute on function public.review_correction_request(bigint,text,text) from public,anon;
grant execute on function public.review_correction_request(bigint,text,text) to authenticated;
