-- sharkAttend production schema
create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  employee_no text not null unique check (employee_no ~ '^[0-9]+$'),
  name text not null,
  role text not null default 'employee' check (role in ('employee','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.attendance_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  work_date date not null,
  clock_in timestamptz,
  clock_out timestamptz,
  created_at timestamptz not null default now(),
  constraint attendance_order check (clock_out is null or (clock_in is not null and clock_out >= clock_in)),
  constraint attendance_one_day unique (user_id, work_date)
);

create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  category text not null default 'general' check (category in ('general','attendance','holiday','event','important','system')),
  created_by uuid references auth.users(id) on delete set null,
  published_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.employee_permissions (
  user_id uuid primary key references auth.users(id) on delete cascade,
  can_manage_employees boolean not null default false,
  can_manage_permissions boolean not null default false,
  can_reset_passwords boolean not null default false,
  can_manage_announcements boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  title text not null,
  body text not null,
  kind text not null default 'general' check (kind in ('general','attendance','announcement','important','system')),
  created_at timestamptz not null default now(),
  expires_at timestamptz
);

alter table public.profiles enable row level security;
alter table public.attendance_records enable row level security;
alter table public.announcements enable row level security;
alter table public.employee_permissions enable row level security;
alter table public.notifications enable row level security;

create schema if not exists private;
create or replace function private.is_admin()
returns boolean language sql stable security definer set search_path='' as $$
  select exists(select 1 from public.profiles where user_id=auth.uid() and role='admin');
$$;
revoke all on function private.is_admin() from public, anon;
grant execute on function private.is_admin() to authenticated;

revoke all on public.profiles from anon, authenticated;
revoke all on public.attendance_records from anon, authenticated;
revoke all on public.announcements from anon, authenticated;
revoke all on public.employee_permissions from anon, authenticated;
revoke all on public.notifications from anon, authenticated;
grant select on public.profiles, public.attendance_records, public.announcements, public.employee_permissions, public.notifications to authenticated;

drop policy if exists profile_read_own on public.profiles;
drop policy if exists profiles_read_all_authenticated on public.profiles;
drop policy if exists profiles_read_self_or_admin on public.profiles;
create policy profiles_read_self_or_admin on public.profiles for select to authenticated using ((select auth.uid())=user_id or private.is_admin());

drop policy if exists attendance_read_own on public.attendance_records;
drop policy if exists attendance_read_all_authenticated on public.attendance_records;
drop policy if exists attendance_read_own_or_admin on public.attendance_records;
create policy attendance_read_own_or_admin on public.attendance_records for select to authenticated using ((select auth.uid())=user_id or private.is_admin());

drop policy if exists announcements_read_authenticated on public.announcements;
create policy announcements_read_authenticated on public.announcements for select to authenticated using (true);

drop policy if exists permissions_read_own on public.employee_permissions;
create policy permissions_read_own on public.employee_permissions for select to authenticated using ((select auth.uid())=user_id);

drop policy if exists notifications_read_relevant on public.notifications;
create policy notifications_read_relevant on public.notifications for select to authenticated using (user_id is null or user_id=(select auth.uid()));

create or replace function public.clock_attendance(p_action text)
returns public.attendance_records
language plpgsql security definer set search_path=''
as $$
declare
  v_uid uuid := auth.uid();
  v_now timestamptz := now();
  v_work_date date := (v_now at time zone 'Asia/Taipei')::date;
  v_row public.attendance_records;
begin
  if v_uid is null then raise exception 'Not authenticated'; end if;
  if p_action not in ('in','out') then raise exception 'Invalid action'; end if;
  if p_action='in' then
    insert into public.attendance_records(user_id,work_date,clock_in)
    values(v_uid,v_work_date,v_now)
    on conflict(user_id,work_date) do nothing returning * into v_row;
    if v_row.id is null then raise exception 'Already clocked in today'; end if;
  else
    update public.attendance_records set clock_out=v_now
    where user_id=v_uid and work_date=v_work_date and clock_in is not null and clock_out is null
    returning * into v_row;
    if v_row.id is null then raise exception 'No open clock-in found today'; end if;
  end if;
  return v_row;
end;
$$;
revoke execute on function public.clock_attendance(text) from public, anon;
grant execute on function public.clock_attendance(text) to authenticated;
