-- sharkAttend v0.1 schema
create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  employee_no text not null unique check (employee_no ~ '^[0-9]+$'),
  name text not null,
  created_at timestamptz not null default now()
);
create table if not exists public.attendance_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  work_date date not null,
  clock_in timestamptz,
  clock_out timestamptz,
  created_at timestamptz not null default now(),
  constraint attendance_order check (clock_out is null or (clock_in is not null and clock_out >= clock_in)),
  constraint attendance_one_day unique (user_id, work_date)
);
create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  published_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);
alter table public.profiles enable row level security;
alter table public.attendance_records enable row level security;
alter table public.announcements enable row level security;
revoke all on public.profiles from anon, authenticated;
revoke all on public.attendance_records from anon, authenticated;
revoke all on public.announcements from anon, authenticated;
grant select on public.profiles to authenticated;
grant select on public.attendance_records to authenticated;
grant select on public.announcements to authenticated;
create policy "profile_read_own" on public.profiles for select to authenticated using ((select auth.uid()) = user_id);
create policy "attendance_read_own" on public.attendance_records for select to authenticated using ((select auth.uid()) = user_id);
create policy "announcements_read_authenticated" on public.announcements for select to authenticated using (true);
create or replace function public.clock_attendance(p_action text)
returns public.attendance_records
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_now timestamptz := now();
  v_work_date date := (v_now at time zone 'Asia/Taipei')::date;
  v_row public.attendance_records;
begin
  if v_uid is null then raise exception 'Not authenticated'; end if;
  if p_action not in ('in', 'out') then raise exception 'Invalid action'; end if;
  if p_action = 'in' then
    insert into public.attendance_records(user_id, work_date, clock_in)
    values (v_uid, v_work_date, v_now)
    on conflict (user_id, work_date) do nothing
    returning * into v_row;
    if v_row.id is null then raise exception 'Already clocked in today'; end if;
  else
    update public.attendance_records set clock_out = v_now
    where user_id = v_uid and work_date = v_work_date and clock_in is not null and clock_out is null
    returning * into v_row;
    if v_row.id is null then raise exception 'No open clock-in found today'; end if;
  end if;
  return v_row;
end;
$$;
revoke execute on function public.clock_attendance(text) from public, anon;
grant execute on function public.clock_attendance(text) to authenticated;
insert into public.announcements(title, body, published_at)
select 'SharkAttend打卡咯', '記得打卡', '2026-08-28 09:00:00+08'::timestamptz
where not exists (select 1 from public.announcements where title = 'SharkAttend打卡咯');
