"use client";

import { useCallback, useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";

type Perms={can_manage_employees:boolean;can_manage_permissions:boolean;can_reset_passwords:boolean};
type Employee={user_id:string;employee_no:string;name:string;role:"employee"|"admin";employee_permissions?:Perms[]|Perms|null};
const emptyPerms:Perms={can_manage_employees:false,can_manage_permissions:false,can_reset_passwords:false};
function normalizePerms(v:Employee["employee_permissions"]):Perms{if(Array.isArray(v))return v[0]??emptyPerms;return v??emptyPerms}

async function edgeErrorMessage(error: unknown){
 const fallback=error instanceof Error?error.message:"Edge Function request failed";
 const context=(error as {context?:unknown}|null)?.context as {clone?:()=>Response;json?:()=>Promise<unknown>}|undefined;
 try{
  const response=context?.clone?.();
  const payload=(response?await response.json():context?.json?await context.json():null) as {error?:string}|null;
  return payload?.error||fallback;
 }catch{return fallback}
}

export default function AdminPanel(){
 const[employees,setEmployees]=useState<Employee[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[newNo,setNewNo]=useState(""),[newName,setNewName]=useState(""),[newRole,setNewRole]=useState<"employee"|"admin">("employee"),[resetPasswords,setResetPasswords]=useState<Record<string,string>>({}),[busy,setBusy]=useState<string|null>(null);
 const invoke=useCallback(async(body:Record<string,unknown>)=>{if(!supabase)throw new Error("Supabase unavailable");const{data,error}=await supabase.functions.invoke("admin-employees",{body});if(error)throw new Error(await edgeErrorMessage(error));if(data?.error)throw new Error(data.error);return data},[]);
 const load=useCallback(async()=>{setLoading(true);setMessage("");try{const data=await invoke({action:"list"});setEmployees(data?.employees??[])}catch(e){setMessage(e instanceof Error?e.message:"讀取員工失敗")}finally{setLoading(false)}},[invoke]);
 useEffect(()=>{load()},[load]);
 async function addEmployee(){if(!newNo.trim()||!newName.trim()){setMessage("請輸入員工編號與姓名");return}setBusy("create");setMessage("");try{await invoke({action:"create",employeeNo:newNo,name:newName,password:"123456",role:newRole});setMessage(`已新增 ${newNo} / ${newName}，預設密碼 123456`);setNewNo("");setNewName("");setNewRole("employee");await load()}catch(e){setMessage(e instanceof Error?e.message:"新增失敗")}setBusy(null)}
 async function savePermissions(emp:Employee,role:"employee"|"admin",permissions:Perms){setBusy(emp.user_id);setMessage("");try{await invoke({action:"update_permissions",userId:emp.user_id,role,permissions});setEmployees(p=>p.map(x=>x.user_id===emp.user_id?{...x,role,employee_permissions:permissions}:x));setMessage(`已更新 ${emp.name} 的權限`)}catch(e){setMessage(e instanceof Error?e.message:"更新失敗")}setBusy(null)}
 async function resetPassword(emp:Employee){const password=resetPasswords[emp.user_id]??"";if(password.length<6){setMessage("新密碼至少 6 碼");return}setBusy(`pw-${emp.user_id}`);setMessage("");try{await invoke({action:"reset_password",userId:emp.user_id,password});setMessage(`已重設 ${emp.name} 的密碼`);setResetPasswords(p=>({...p,[emp.user_id]:""}))}catch(e){setMessage(e instanceof Error?e.message:"重設密碼失敗")}setBusy(null)}
 return <div className="admin-page"><div className="section-title"><span className="eyebrow">ADMIN</span><h1>員工管理</h1><p>新增員工、設定角色與管理權限。</p></div><section className="admin-card add-employee-card"><div className="admin-card-title"><h2>新增員工</h2><p>新員工預設密碼固定為 123456，可登入後自行修改。</p></div><div className="admin-form-grid"><label>員工編號<input inputMode="numeric" value={newNo} onChange={e=>setNewNo(e.target.value)} placeholder="例如 005" /></label><label>姓名<input value={newName} onChange={e=>setNewName(e.target.value)} placeholder="員工姓名" /></label><label>角色<select value={newRole} onChange={e=>setNewRole(e.target.value as "employee"|"admin")}><option value="employee">一般員工</option><option value="admin">管理員</option></select></label><label>預設密碼<input value="123456" readOnly /></label></div><button className="admin-primary" disabled={busy==="create"} onClick={addEmployee}>{busy==="create"?"新增中…":"新增員工"}</button></section>{message&&<div className="admin-message">{message}</div>}<div className="employee-list">{loading&&<div className="empty-card">讀取員工中…</div>}{!loading&&employees.map(emp=><EmployeeCard key={emp.user_id} emp={emp} perms={normalizePerms(emp.employee_permissions)} busy={busy} resetPasswordValue={resetPasswords[emp.user_id]??""} onResetValue={v=>setResetPasswords(p=>({...p,[emp.user_id]:v}))} onResetDefault={()=>setResetPasswords(p=>({...p,[emp.user_id]:"123456"}))} onReset={()=>resetPassword(emp)} onSave={(role,p)=>savePermissions(emp,role,p)} />)}</div></div>
}

function EmployeeCard({emp,perms,busy,resetPasswordValue,onResetValue,onResetDefault,onReset,onSave}:{emp:Employee;perms:Perms;busy:string|null;resetPasswordValue:string;onResetValue:(v:string)=>void;onResetDefault:()=>void;onReset:()=>void;onSave:(r:"employee"|"admin",p:Perms)=>void}){
 const[role,setRole]=useState(emp.role),[localPerms,setLocalPerms]=useState(perms);useEffect(()=>{setRole(emp.role);setLocalPerms(perms)},[emp.role,perms.can_manage_employees,perms.can_manage_permissions,perms.can_reset_passwords]);const setPerm=(k:keyof Perms,v:boolean)=>setLocalPerms(p=>({...p,[k]:v}));
 return <section className="admin-card employee-card"><div className="employee-head"><div className="employee-avatar">{emp.name.slice(0,1).toUpperCase()}</div><div className="employee-ident"><strong>{emp.name}</strong><span>#{emp.employee_no}</span></div><span className={role==="admin"?"role-badge admin":"role-badge"}>{role==="admin"?"管理員":"員工"}</span></div><div className="role-row"><label>角色<select value={role} onChange={e=>{const r=e.target.value as "employee"|"admin";setRole(r);if(r==="employee")setLocalPerms(emptyPerms)}}><option value="employee">一般員工</option><option value="admin">管理員</option></select></label></div><div className="permission-grid"><label><input type="checkbox" disabled={role!=="admin"} checked={localPerms.can_manage_employees} onChange={e=>setPerm("can_manage_employees",e.target.checked)} /><span><b>員工管理</b><small>查看與新增員工</small></span></label><label><input type="checkbox" disabled={role!=="admin"} checked={localPerms.can_manage_permissions} onChange={e=>setPerm("can_manage_permissions",e.target.checked)} /><span><b>權限管理</b><small>變更角色與權限</small></span></label><label><input type="checkbox" disabled={role!=="admin"} checked={localPerms.can_reset_passwords} onChange={e=>setPerm("can_reset_passwords",e.target.checked)} /><span><b>密碼管理</b><small>替員工重設密碼</small></span></label></div><button className="admin-secondary" disabled={busy===emp.user_id} onClick={()=>onSave(role,localPerms)}>{busy===emp.user_id?"儲存中…":"儲存權限"}</button><div className="password-reset"><div><strong>重設密碼</strong><small>至少 6 碼；可一鍵恢復預設 123456。</small></div><div className="inline-input"><input value={resetPasswordValue} onChange={e=>onResetValue(e.target.value)} placeholder="新密碼" /><button type="button" onClick={onResetDefault}>123456</button></div><button className="reset-btn" disabled={busy===`pw-${emp.user_id}`} onClick={onReset}>{busy===`pw-${emp.user_id}`?"處理中…":"更新密碼"}</button></div></section>
}
