"use client";

import { useCallback, useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import type { TranslationKey } from "@/lib/i18n";

type T=(key:TranslationKey)=>string;
type Perms={can_manage_employees:boolean;can_manage_permissions:boolean;can_reset_passwords:boolean;can_manage_announcements:boolean;can_manage_attendance:boolean};
type Employee={user_id:string;employee_no:string;name:string;role:"employee"|"admin";employee_permissions?:Perms[]|Perms|null};
const emptyPerms:Perms={can_manage_employees:false,can_manage_permissions:false,can_reset_passwords:false,can_manage_announcements:false,can_manage_attendance:false};
function normalizePerms(v:Employee["employee_permissions"]):Perms{if(Array.isArray(v))return v[0]??emptyPerms;return v??emptyPerms}
async function edgeErrorMessage(error:unknown){const fallback=error instanceof Error?error.message:"Edge Function request failed";const context=(error as {context?:unknown}|null)?.context as {clone?:()=>Response;json?:()=>Promise<unknown>}|undefined;try{const response=context?.clone?.();const payload=(response?await response.json():context?.json?await context.json():null) as {error?:string}|null;return payload?.error||fallback}catch{return fallback}}

export default function AdminPanel({onBack,t}:{onBack?:()=>void;t:T}){
 const[employees,setEmployees]=useState<Employee[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[newNo,setNewNo]=useState(""),[newName,setNewName]=useState(""),[newRole,setNewRole]=useState<"employee"|"admin">("employee"),[resetPasswords,setResetPasswords]=useState<Record<string,string>>({}),[busy,setBusy]=useState<string|null>(null),[expanded,setExpanded]=useState<string|null>(null),[showAdd,setShowAdd]=useState(false);
 const invoke=useCallback(async(body:Record<string,unknown>)=>{if(!supabase)throw new Error("Supabase unavailable");const{data,error}=await supabase.functions.invoke("admin-employees",{body});if(error)throw new Error(await edgeErrorMessage(error));if(data?.error)throw new Error(data.error);return data},[]);
 const load=useCallback(async()=>{setLoading(true);setMessage("");try{const data=await invoke({action:"list"});setEmployees(data?.employees??[])}catch(e){setMessage(e instanceof Error?e.message:"Load failed")}finally{setLoading(false)}},[invoke]);
 useEffect(()=>{load()},[load]);
 async function addEmployee(){if(!newNo.trim()||!newName.trim()){setMessage(`${t("employeeNo")} / ${t("name")}`);return}setBusy("create");setMessage("");try{await invoke({action:"create",employeeNo:newNo,name:newName,password:"123456",role:newRole});setMessage(`${t("created")} ${newNo} / ${newName}`);setNewNo("");setNewName("");setNewRole("employee");setShowAdd(false);await load()}catch(e){setMessage(e instanceof Error?e.message:"Create failed")}setBusy(null)}
 async function savePermissions(emp:Employee,role:"employee"|"admin",permissions:Perms){setBusy(emp.user_id);setMessage("");try{await invoke({action:"update_permissions",userId:emp.user_id,role,permissions});setEmployees(p=>p.map(x=>x.user_id===emp.user_id?{...x,role,employee_permissions:permissions}:x));setMessage(`${emp.name} · ${t("permissions")}`)}catch(e){setMessage(e instanceof Error?e.message:"Update failed")}setBusy(null)}
 async function resetPassword(emp:Employee){const password=resetPasswords[emp.user_id]??"";if(password.length<6){setMessage(t("passwordMin"));return}setBusy(`pw-${emp.user_id}`);setMessage("");try{await invoke({action:"reset_password",userId:emp.user_id,password});setMessage(`${emp.name} · ${t("passwordUpdated")}`);setResetPasswords(p=>({...p,[emp.user_id]:""}))}catch(e){setMessage(e instanceof Error?e.message:"Reset failed")}setBusy(null)}
 return <div className="settings-page"><div className="subpage-header">{onBack&&<button className="back-button" onClick={onBack}>{t("backMine")}</button>}<h1>{t("peopleManagement")}</h1><button className="text-action" onClick={()=>setShowAdd(v=>!v)}>{showAdd?t("cancel"):t("add")}</button></div>{showAdd&&<section className="ios-form"><div className="ios-field"><span>{t("employeeNo")}</span><input inputMode="numeric" value={newNo} onChange={e=>setNewNo(e.target.value)} placeholder="005" /></div><div className="ios-field"><span>{t("name")}</span><input value={newName} onChange={e=>setNewName(e.target.value)} /></div><div className="ios-field"><span>{t("role")}</span><select value={newRole} onChange={e=>setNewRole(e.target.value as "employee"|"admin")}><option value="employee">{t("employee")}</option><option value="admin">{t("admin")}</option></select></div><div className="ios-field"><span>{t("defaultPassword")}</span><b>123456</b></div><button className="ios-primary" disabled={busy==="create"} onClick={addEmployee}>{busy==="create"?t("saving"):t("newPerson")}</button></section>}{message&&<div className="inline-status">{message}</div>}<div className="settings-label">{t("people")} · {employees.length}</div><section className="settings-group employee-group">{loading&&<div className="settings-loading">{t("loading")}</div>}{!loading&&employees.map(emp=><EmployeeRow key={emp.user_id} emp={emp} expanded={expanded===emp.user_id} onToggle={()=>setExpanded(v=>v===emp.user_id?null:emp.user_id)} perms={normalizePerms(emp.employee_permissions)} busy={busy} resetPasswordValue={resetPasswords[emp.user_id]??""} onResetValue={v=>setResetPasswords(p=>({...p,[emp.user_id]:v}))} onResetDefault={()=>setResetPasswords(p=>({...p,[emp.user_id]:"123456"}))} onReset={()=>resetPassword(emp)} onSave={(role,p)=>savePermissions(emp,role,p)} t={t}/>)}</section></div>
}

function EmployeeRow({emp,expanded,onToggle,perms,busy,resetPasswordValue,onResetValue,onResetDefault,onReset,onSave,t}:{emp:Employee;expanded:boolean;onToggle:()=>void;perms:Perms;busy:string|null;resetPasswordValue:string;onResetValue:(v:string)=>void;onResetDefault:()=>void;onReset:()=>void;onSave:(r:"employee"|"admin",p:Perms)=>void;t:T}){
 const[role,setRole]=useState(emp.role),[localPerms,setLocalPerms]=useState(perms);useEffect(()=>{setRole(emp.role);setLocalPerms(perms)},[emp.role,perms.can_manage_employees,perms.can_manage_permissions,perms.can_reset_passwords,perms.can_manage_announcements,perms.can_manage_attendance]);const setPerm=(k:keyof Perms,v:boolean)=>setLocalPerms(p=>({...p,[k]:v}));
 return <div className="employee-row-wrap"><button className="employee-row" onClick={onToggle}><div className="employee-mini-avatar">{emp.name.slice(0,1).toUpperCase()}</div><div className="employee-row-main"><strong>{emp.name}</strong><span>#{emp.employee_no} · {role==="admin"?t("admin"):t("employee")}</span></div><span className={expanded?"chevron open":"chevron"}>›</span></button>{expanded&&<div className="employee-detail"><div className="ios-field"><span>{t("role")}</span><select value={role} onChange={e=>{const r=e.target.value as "employee"|"admin";setRole(r);if(r==="employee")setLocalPerms(emptyPerms)}}><option value="employee">{t("employee")}</option><option value="admin">{t("admin")}</option></select></div><div className="switch-list"><Toggle label={t("employeeManagement")} note={t("employeeManagementNote")} disabled={role!=="admin"} checked={localPerms.can_manage_employees} onChange={v=>setPerm("can_manage_employees",v)}/><Toggle label={t("permissionManagement")} note={t("permissionManagementNote")} disabled={role!=="admin"} checked={localPerms.can_manage_permissions} onChange={v=>setPerm("can_manage_permissions",v)}/><Toggle label={t("passwordManagement")} note={t("passwordManagementNote")} disabled={role!=="admin"} checked={localPerms.can_reset_passwords} onChange={v=>setPerm("can_reset_passwords",v)}/><Toggle label={t("announcementPermission")} note={t("announcementPermissionNote")} disabled={role!=="admin"} checked={localPerms.can_manage_announcements} onChange={v=>setPerm("can_manage_announcements",v)}/><Toggle label={t("attendancePermission")} note={t("attendancePermissionNote")} disabled={role!=="admin"} checked={localPerms.can_manage_attendance} onChange={v=>setPerm("can_manage_attendance",v)}/></div><button className="ios-secondary" disabled={busy===emp.user_id} onClick={()=>onSave(role,localPerms)}>{busy===emp.user_id?t("saving"):t("savePermissions")}</button><div className="reset-section"><div className="reset-heading"><strong>{t("resetPassword")}</strong><span>6+</span></div><div className="reset-inline"><input type="password" value={resetPasswordValue} onChange={e=>onResetValue(e.target.value)} placeholder={t("newPassword")}/><button type="button" onClick={onResetDefault}>123456</button></div><button className="danger-light" disabled={busy===`pw-${emp.user_id}`} onClick={onReset}>{busy===`pw-${emp.user_id}`?t("saving"):t("updatePassword")}</button></div></div>}</div>
}
function Toggle({label,note,checked,disabled,onChange}:{label:string;note:string;checked:boolean;disabled:boolean;onChange:(v:boolean)=>void}){return <label className="switch-row"><span><b>{label}</b><small>{note}</small></span><input type="checkbox" checked={checked} disabled={disabled} onChange={e=>onChange(e.target.checked)}/></label>}
