"use client";

import { useCallback,useEffect,useMemo,useState } from "react";
import { supabase } from "@/lib/supabase";
import type { TranslationKey } from "@/lib/i18n";

type T=(key:TranslationKey)=>string;
type Profile={user_id:string;employee_no:string;name:string};
type AttendanceRecord={user_id:string;work_date:string;clock_in:string|null;clock_out:string|null;employee_no:string;name:string};
type LeaveRequest={id:number;user_id:string;leave_type:string;start_date:string;end_date:string;reason:string|null;status:string;created_at:string};
type CorrectionRequest={id:number;user_id:string;work_date:string;requested_clock_in:string|null;requested_clock_out:string|null;reason:string;status:string;created_at:string};
type Settings={work_start:string;work_end:string;late_grace_minutes:number};
type Schedule={id:number;user_id:string;work_date:string;start_time:string|null;end_time:string|null;is_workday:boolean;note:string|null};

function toLocalInput(date:string,time:string){return `${date}T${time.slice(0,5)}`}
function minutesBetween(a:string|null,b:string|null){if(!a||!b)return 0;return Math.max(0,Math.floor((new Date(b).getTime()-new Date(a).getTime())/60000))}
function statusText(t:T,s:string){return s==="approved"?t("approved"):s==="rejected"?t("rejected"):t("pending")}
function leaveTypeText(t:T,s:string){return s==="annual"?t("annualLeave"):s==="sick"?t("sickLeave"):s==="personal"?t("personalLeave"):t("unpaidLeave")}

export function ApplicationsPage({userId,isAdmin,t}:{userId:string;isAdmin:boolean;t:T}){
 const[mode,setMode]=useState<"correction"|"leave"|"mine">("correction"),[leaves,setLeaves]=useState<LeaveRequest[]>([]),[corrections,setCorrections]=useState<CorrectionRequest[]>([]),[profiles,setProfiles]=useState<Profile[]>([]),[message,setMessage]=useState("");
 const[leaveType,setLeaveType]=useState("annual"),[startDate,setStartDate]=useState(""),[endDate,setEndDate]=useState(""),[leaveReason,setLeaveReason]=useState("");
 const[workDate,setWorkDate]=useState(""),[inTime,setInTime]=useState(""),[outTime,setOutTime]=useState(""),[correctionReason,setCorrectionReason]=useState("");
 const load=useCallback(async()=>{if(!supabase)return;const[{data:l},{data:c},{data:p}]=await Promise.all([supabase.from("leave_requests").select("*").order("created_at",{ascending:false}),supabase.from("correction_requests").select("*").order("created_at",{ascending:false}),isAdmin?supabase.from("profiles").select("user_id,employee_no,name").order("employee_no"):Promise.resolve({data:[] as Profile[]})]);setLeaves((l??[]) as LeaveRequest[]);setCorrections((c??[]) as CorrectionRequest[]);setProfiles((p??[]) as Profile[])},[isAdmin]);
 useEffect(()=>{load()},[load]);
 const names=useMemo(()=>new Map(profiles.map(p=>[p.user_id,p])),[profiles]);
 async function submitLeave(){if(!supabase||!startDate||!endDate)return;setMessage("");const{error}=await supabase.from("leave_requests").insert({user_id:userId,leave_type:leaveType,start_date:startDate,end_date:endDate,reason:leaveReason||null});setMessage(error?error.message:t("requestSubmitted"));if(!error){setLeaveReason("");await load()}}
 async function submitCorrection(){if(!supabase||!workDate||(!inTime&&!outTime)||!correctionReason.trim())return;setMessage("");const payload={user_id:userId,work_date:workDate,requested_clock_in:inTime?new Date(inTime).toISOString():null,requested_clock_out:outTime?new Date(outTime).toISOString():null,reason:correctionReason};const{error}=await supabase.from("correction_requests").insert(payload);setMessage(error?error.message:t("requestSubmitted"));if(!error){setCorrectionReason("");setInTime("");setOutTime("");await load()}}
 async function review(kind:"leave"|"correction",id:number,status:"approved"|"rejected"){if(!supabase)return;const fn=kind==="leave"?"review_leave_request":"review_correction_request";const{error}=await supabase.rpc(fn,{p_id:id,p_status:status,p_note:null});setMessage(error?error.message:t("reviewed"));if(!error)await load()}
 const myLeaves=leaves.filter(x=>x.user_id===userId),myCorrections=corrections.filter(x=>x.user_id===userId);const pendingLeaves=leaves.filter(x=>x.status==="pending"),pendingCorrections=corrections.filter(x=>x.status==="pending");
 return <div className="list-page"><div className="section-title"><span className="eyebrow">REQUESTS</span><h1>{t("requestCenter")}</h1></div><div className="segmented request-tabs"><button className={mode==="correction"?"active":""} onClick={()=>setMode("correction")}>{t("correction")}</button><button className={mode==="leave"?"active":""} onClick={()=>setMode("leave")}>{t("leave")}</button><button className={mode==="mine"?"active":""} onClick={()=>setMode("mine")}>{t("myRequests")}</button></div>{message&&<div className="inline-status">{message}</div>}
 {mode==="correction"&&<section className="ios-form suite-form"><div className="ios-field"><span>{t("scheduleDate")}</span><input type="date" value={workDate} onChange={e=>{setWorkDate(e.target.value);if(e.target.value){setInTime(toLocalInput(e.target.value,"09:00"));setOutTime(toLocalInput(e.target.value,"18:00"))}}}/></div><div className="ios-field"><span>{t("requestedClockIn")}</span><input type="datetime-local" value={inTime} onChange={e=>setInTime(e.target.value)}/></div><div className="ios-field"><span>{t("requestedClockOut")}</span><input type="datetime-local" value={outTime} onChange={e=>setOutTime(e.target.value)}/></div><div className="ios-field"><span>{t("reason")}</span><input value={correctionReason} onChange={e=>setCorrectionReason(e.target.value)}/></div><button className="ios-primary" onClick={submitCorrection}>{t("submit")}</button></section>}
 {mode==="leave"&&<section className="ios-form suite-form"><div className="ios-field"><span>{t("leaveType")}</span><select value={leaveType} onChange={e=>setLeaveType(e.target.value)}><option value="annual">{t("annualLeave")}</option><option value="sick">{t("sickLeave")}</option><option value="personal">{t("personalLeave")}</option><option value="unpaid">{t("unpaidLeave")}</option></select></div><div className="ios-field"><span>{t("startDate")}</span><input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></div><div className="ios-field"><span>{t("endDate")}</span><input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)}/></div><div className="ios-field"><span>{t("reason")}</span><input value={leaveReason} onChange={e=>setLeaveReason(e.target.value)}/></div><button className="ios-primary" onClick={submitLeave}>{t("submit")}</button></section>}
 {mode==="mine"&&<div className="settings-group request-list">{[...myCorrections.map(x=>({kind:"correction" as const,id:x.id,date:x.work_date,title:t("correction"),status:x.status,detail:x.reason})),...myLeaves.map(x=>({kind:"leave" as const,id:x.id,date:x.start_date,title:leaveTypeText(t,x.leave_type),status:x.status,detail:`${x.start_date} → ${x.end_date}`}))].sort((a,b)=>b.date.localeCompare(a.date)).map(x=><div className="request-row" key={`${x.kind}-${x.id}`}><div><strong>{x.title}</strong><small>{x.detail}</small></div><span className={`status-pill ${x.status}`}>{statusText(t,x.status)}</span></div>)}{!myLeaves.length&&!myCorrections.length&&<div className="empty-line">{t("noRequests")}</div>}</div>}
 {isAdmin&&(pendingLeaves.length>0||pendingCorrections.length>0)&&<><div className="settings-label">{t("review")}</div><section className="settings-group request-list">{pendingCorrections.map(x=><ReviewRow key={`c-${x.id}`} title={`${names.get(x.user_id)?.name??"—"} · ${t("correction")}`} detail={`${x.work_date} · ${x.reason}`} onApprove={()=>review("correction",x.id,"approved")} onReject={()=>review("correction",x.id,"rejected")} t={t}/>)}{pendingLeaves.map(x=><ReviewRow key={`l-${x.id}`} title={`${names.get(x.user_id)?.name??"—"} · ${leaveTypeText(t,x.leave_type)}`} detail={`${x.start_date} → ${x.end_date}`} onApprove={()=>review("leave",x.id,"approved")} onReject={()=>review("leave",x.id,"rejected")} t={t}/>)}</section></>}
 </div>
}
function ReviewRow({title,detail,onApprove,onReject,t}:{title:string;detail:string;onApprove:()=>void;onReject:()=>void;t:T}){return <div className="review-row"><div><strong>{title}</strong><small>{detail}</small></div><div><button onClick={onReject}>{t("reject")}</button><button className="approve" onClick={onApprove}>{t("approve")}</button></div></div>}

export function AttendanceAdminPage({onBack,t}:{onBack:()=>void;t:T}){
 const[settings,setSettings]=useState<Settings>({work_start:"09:00",work_end:"18:00",late_grace_minutes:0}),[profiles,setProfiles]=useState<Profile[]>([]),[schedules,setSchedules]=useState<Schedule[]>([]),[userId,setUserId]=useState(""),[date,setDate]=useState(""),[isWorkday,setIsWorkday]=useState(true),[start,setStart]=useState("09:00"),[end,setEnd]=useState("18:00"),[note,setNote]=useState(""),[message,setMessage]=useState("");
 const load=useCallback(async()=>{if(!supabase)return;const[{data:s},{data:p},{data:sch}]=await Promise.all([supabase.from("attendance_settings").select("work_start,work_end,late_grace_minutes").eq("id",1).single(),supabase.from("profiles").select("user_id,employee_no,name").order("employee_no"),supabase.from("employee_schedules").select("*").gte("work_date",new Date().toISOString().slice(0,10)).order("work_date")]);if(s)setSettings(s as Settings);setProfiles((p??[]) as Profile[]);setSchedules((sch??[]) as Schedule[]);if(!userId&&p?.[0])setUserId(p[0].user_id)},[userId]);useEffect(()=>{load()},[load]);
 async function saveRules(){if(!supabase)return;const{error}=await supabase.rpc("update_attendance_settings",{p_start:settings.work_start,p_end:settings.work_end,p_grace:settings.late_grace_minutes});setMessage(error?error.message:t("saved"))}
 async function saveSchedule(){if(!supabase||!userId||!date)return;const row={user_id:userId,work_date:date,start_time:isWorkday?start:null,end_time:isWorkday?end:null,is_workday:isWorkday,note:note||null,updated_at:new Date().toISOString()};const{error}=await supabase.from("employee_schedules").upsert(row,{onConflict:"user_id,work_date"});setMessage(error?error.message:t("saved"));if(!error){setNote("");await load()}}
 const names=useMemo(()=>new Map(profiles.map(p=>[p.user_id,p])),[profiles]);
 return <div className="settings-page"><div className="subpage-header"><button className="back-button" onClick={onBack}>{t("backMine")}</button><h1>{t("attendanceManagement")}</h1><span/></div>{message&&<div className="inline-status">{message}</div>}<div className="settings-label">{t("workRules")}</div><section className="ios-form"><div className="ios-field"><span>{t("workStart")}</span><input type="time" value={settings.work_start.slice(0,5)} onChange={e=>setSettings(s=>({...s,work_start:e.target.value}))}/></div><div className="ios-field"><span>{t("workEnd")}</span><input type="time" value={settings.work_end.slice(0,5)} onChange={e=>setSettings(s=>({...s,work_end:e.target.value}))}/></div><div className="ios-field"><span>{t("lateGrace")}</span><input type="number" min="0" max="180" value={settings.late_grace_minutes} onChange={e=>setSettings(s=>({...s,late_grace_minutes:Number(e.target.value)}))}/></div><button className="ios-primary" onClick={saveRules}>{t("save")}</button></section><div className="settings-label">{t("schedule")}</div><section className="ios-form"><div className="ios-field"><span>{t("selectEmployee")}</span><select value={userId} onChange={e=>setUserId(e.target.value)}>{profiles.map(p=><option key={p.user_id} value={p.user_id}>{p.employee_no} · {p.name}</option>)}</select></div><div className="ios-field"><span>{t("scheduleDate")}</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><div className="ios-field"><span>{t("status")}</span><select value={isWorkday?"work":"off"} onChange={e=>setIsWorkday(e.target.value==="work")}><option value="work">{t("workday")}</option><option value="off">{t("dayOff")}</option></select></div>{isWorkday&&<><div className="ios-field"><span>{t("workStart")}</span><input type="time" value={start} onChange={e=>setStart(e.target.value)}/></div><div className="ios-field"><span>{t("workEnd")}</span><input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></div></>}<div className="ios-field"><span>{t("scheduleNote")}</span><input value={note} onChange={e=>setNote(e.target.value)}/></div><button className="ios-primary" onClick={saveSchedule}>{t("assignSchedule")}</button></section><div className="settings-label">{t("upcomingSchedules")}</div><section className="settings-group">{schedules.map(s=><div className="schedule-row" key={s.id}><div><strong>{s.work_date} · {names.get(s.user_id)?.name??"—"}</strong><small>{s.is_workday?`${s.start_time?.slice(0,5)}–${s.end_time?.slice(0,5)}`:t("dayOff")}{s.note?` · ${s.note}`:""}</small></div></div>)}{!schedules.length&&<div className="empty-line">—</div>}</section></div>
}

export function RecordsDashboard({records,profiles,t}:{records:AttendanceRecord[];profiles:Profile[];t:T}){
 const now=new Date();const[currentMonth,setCurrentMonth]=useState(`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}`),[employee,setEmployee]=useState("all"),[settings,setSettings]=useState<Settings>({work_start:"09:00",work_end:"18:00",late_grace_minutes:0}),[schedules,setSchedules]=useState<Schedule[]>([]),[leaves,setLeaves]=useState<LeaveRequest[]>([]);
 useEffect(()=>{if(!supabase)return;Promise.all([supabase.from("attendance_settings").select("work_start,work_end,late_grace_minutes").eq("id",1).single(),supabase.from("employee_schedules").select("*").gte("work_date",`${currentMonth}-01`).lte("work_date",`${currentMonth}-31`),supabase.from("leave_requests").select("*").eq("status","approved").lte("start_date",`${currentMonth}-31`).gte("end_date",`${currentMonth}-01`)]).then(([a,b,c])=>{if(a.data)setSettings(a.data as Settings);setSchedules((b.data??[]) as Schedule[]);setLeaves((c.data??[]) as LeaveRequest[])})},[currentMonth]);
 const scheduleMap=useMemo(()=>new Map(schedules.map(s=>[`${s.user_id}|${s.work_date}`,s])),[schedules]);
 const isLeave=(uid:string,date:string)=>leaves.some(l=>l.user_id===uid&&l.start_date<=date&&l.end_date>=date);
 const filtered=useMemo(()=>records.filter(r=>r.work_date.startsWith(currentMonth)&&(employee==="all"||r.user_id===employee)),[records,currentMonth,employee]);
 const rows=filtered.map(r=>{const sch=scheduleMap.get(`${r.user_id}|${r.work_date}`);const start=(sch?.start_time??settings.work_start).slice(0,5),end=(sch?.end_time??settings.work_end).slice(0,5);let late=false,early=false,missing=!r.clock_in||!r.clock_out;if(r.clock_in){const actual=new Date(r.clock_in);const expected=new Date(`${r.work_date}T${start}:00+08:00`);late=actual.getTime()>expected.getTime()+settings.late_grace_minutes*60000}if(r.clock_out){const actual=new Date(r.clock_out);const expected=new Date(`${r.work_date}T${end}:00+08:00`);early=actual.getTime()<expected.getTime()}const leave=isLeave(r.user_id,r.work_date);const status=leave?"leave":missing?"missing":late?"late":early?"early":"normal";return{...r,late,early,missing,leave,status,mins:minutesBetween(r.clock_in,r.clock_out)}});
 const summary={days:rows.filter(r=>r.clock_in).length,late:rows.filter(r=>r.late).length,early:rows.filter(r=>r.early).length,missing:rows.filter(r=>r.missing).length,leave:new Set(leaves.filter(l=>employee==="all"||l.user_id===employee).flatMap(l=>{const out=[];for(let d=new Date(`${l.start_date}T12:00:00+08:00`);d<=new Date(`${l.end_date}T12:00:00+08:00`);d.setDate(d.getDate()+1))out.push(d.toISOString().slice(0,10));return out})).size};
 function exportCsv(){const head=["Date","Employee No","Name","Clock In","Clock Out","Minutes","Status"];const body=rows.map(r=>[r.work_date,r.employee_no,r.name,r.clock_in??"",r.clock_out??"",String(r.mins),r.status]);const csv=[head,...body].map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");const blob=new Blob(["\uFEFF"+csv],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`sharkAttend-${currentMonth}.csv`;a.click();URL.revokeObjectURL(url)}
 const statusLabel=(s:string)=>s==="leave"?t("onLeave"):s==="missing"?t("missing"):s==="late"?t("late"):s==="early"?t("early"):t("normal");
 return <div className="list-page"><div className="section-title"><span className="eyebrow">RECORDS</span><h1>{t("records")}</h1></div><div className="filter-bar"><input className="month-input" type="month" value={currentMonth} onChange={e=>setCurrentMonth(e.target.value)}/><select value={employee} onChange={e=>setEmployee(e.target.value)}><option value="all">{t("allPeople")}</option>{profiles.map(p=><option key={p.user_id} value={p.user_id}>{p.employee_no} · {p.name}</option>)}</select></div><div className="settings-label">{t("monthlySummary")}</div><div className="summary-strip"><Summary label={t("attendanceDays")} value={summary.days}/><Summary label={t("lateCount")} value={summary.late}/><Summary label={t("earlyCount")} value={summary.early}/><Summary label={t("missingCount")} value={summary.missing}/><Summary label={t("leaveDays")} value={summary.leave}/></div><button className="export-button" onClick={exportCsv}>{t("exportCsv")}</button><div className="settings-label">{currentMonth}</div><section className="settings-group">{rows.map(r=><div className="attendance-detail-row" key={`${r.user_id}-${r.work_date}`}><div><strong>{r.work_date} · {r.name}</strong><small>{r.clock_in?new Date(r.clock_in).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}):"--:--"} → {r.clock_out?new Date(r.clock_out).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}):"--:--"} · {Math.floor(r.mins/60)}h {r.mins%60}m</small></div><span className={`status-pill ${r.status}`}>{statusLabel(r.status)}</span></div>)}{!rows.length&&<div className="empty-line">{t("noRecords")}</div>}</section></div>
}
function Summary({label,value}:{label:string;value:number}){return <div><strong>{value}</strong><small>{label}</small></div>}
